package Structs;

public class Crop {
    public double CropType;
    public double PlantMethod;
    public double CalendarType;
    public double SwitchGDD;
    public String PlantingDate;
    public String HarvestDate;

    public double Emergence;
    public double MaxRooting;
    public double Senescence;
    public double Maturity;
    public double HIstart;
    public double Flowering;
    public double YldForm;
    public double GDDmethod;
    public double Tbase;
    public double Tupp;
    public double PolHeatStress;
    public double Tmax_up;
    public double Tmax_lo;
    public double PolColdStress;
    public double Tmin_up;
    public double Tmin_lo;
    public double TrColdStress;
    public double GDD_up;
    public double GDD_lo;
    public double Zmin;
    public double Zmax;
    public double fshape_r;
    public double SxTopQ;
    public double SxBotQ;
    public double SeedSize;
    public double PlantPop;
    public double CCx;
    public double CDC;
    public double CGC;
    public double Kcb;
    public double fage;
    public double WP;
    public double WPy;
    public double fsink;
    public double HI0;
    public double dHI_pre;
    public double a_HI;
    public double b_HI;
    public double dHI0;
    public double Determinant;
    public double exc;
    public double p_up1;
    public double p_up2;
    public double p_up3;
    public double p_up4;
    public double p_lo1;
    public double p_lo2;
    public double p_lo3;
    public double p_lo4;
    public double fshape_w1;
    public double fshape_w2;
    public double fshape_w3;
    public double fshape_w4;


    public String IrrigationFile;
    public String FieldMngtFile;
    public double fshape_b;
    public double PctZmin;
    public double fshape_ex;
    public double ETadj;
    public double Aer;
    public double LagAer;
    public double beta;
    public double a_Tr;
    public double GermThr;
    public double CCmin;
    public double MaxFlowPct;
    public double HIini;
    public double bsted;
    public double bface;

    public double CC0;
    public double SxTop;
    public double SxBot;
    public double[] p_up;
    public double[] p_lo;
    public double[] fshape_w;

    public double tLinSwitch;
    public double dHILinear;
    public double fCO2;

    public int MaxCanopy;
    public int Canopy10Pct;
    public int HIstartCD;
    public int YldFormCD;
    public int FloweringCD;
    public double HIGC;
    public double CanopyDevEnd;
    public double MaxCanopyCD;
}
